#!/bin/bash

TEMPDATADIR=$1
UNMERGEDDATADIR=$2
MERGEDDATADIR=$3

OUTPUTFILE=`find "${TEMPDATADIR}/" -name "*AsAd0*"`
echo ${OUTPUTFILE}
OUTPUTFILE="${OUTPUTFILE/AsAd0_/}"

echo ${OUTPUTFILE}
#touch ${OUTPUTFILE}
cobo-frame-merge ${TEMPDATADIR}/*AsAd0* ${TEMPDATADIR}/*AsAd2* -o ${OUTPUTFILE}

mv ${TEMPDATADIR}/*AsAd* ${UNMERGEDDATADIR}
mv ${TEMPDATADIR}/*.graw ${MERGEDDATADIR}
